### ISSUE TITLE
Possible Typo in Fourier Layer Code

### ISSUE THREAD

**Issue by X1AOX1A** [Chaos96/fourierft#3]
# Possible Typo in Fourier Layer Code

Hey, I noticed that the [scale](https://github.com/Chaos96/fourierft/blob/eb0508ebdab8e8f7ad368a31d454ce9708a7ffc2/peft/src/peft/tuners/fourier/layer.py#L306) is set to a constant `300`. 

Is this a typo? Should the scale be `self.scale[adapter]` instead of `300`?

[/peft/src/peft/tuners/fourier/layer.py#L306](https://github.com/Chaos96/fourierft/blob/eb0508ebdab8e8f7ad368a31d454ce9708a7ffc2/peft/src/peft/tuners/fourier/layer.py#L306)

```python
weight = torch.fft.ifft2(torch.sparse.FloatTensor(indices, spectrum, [self.in_features, self.in_features]).to_dense()).real * 300
```

**Comment by Chaos96** [comment]
Thank you for catching that! You're absolutely right, it should be `self.scale[adapter]` instead of the hardcoded 300. We appreciate your attention to detail. I'll update the code and push the fix as soon as possible. If you spot anything else, please let us know.

**Comment by X1AOX1A** [comment]
You’re welcome! I’m glad I could help.
