### ISSUE TITLE
Can you please give a comparison between fourierft and lora in terms of time complexity?

### ISSUE THREAD

**Issue by xiangmind** [Chaos96/fourierft#6]
For example, how long does it take to finetune llama2-7B&13B with fourierft? Using the similar experimental setting, how long does it take to finetune llama2-7B&13B with lora?

Thanks.

**Comment by zqgao22** [comment]
> For example, how long does it take to finetune llama2-7B&13B with fourierft? Using the similar experimental setting, how long does it take to finetune llama2-7B&13B with lora?
> 
> Thanks.

Thanks for your interest and questions. We will add the time results related to your interest to our arxiv paper. Here are some results:
Device: Single NVIDIA 4090 GPU; Epoch number: 1; Using BF16: True; Model: LLaMA-2-7b; Batch size: 1; target_modules: ["q_proj", "v_proj"].

On the Alpaca dataset: LoRA: 1h42m; FourierFT: 2h47m
On the GSM8K dataset: LoRA: 15m; FourierFT: 19m

Compared with LoRA, FourierFT has the same characteristics in almost all tasks: less GPU memory cost, but slower speed.

Best.
